# Generated by Django 4.2.1 on 2023-08-02 13:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('api', '0002_transactions_original_asset_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletsSort',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('blockchain', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('MATIC', 'Polygon')], max_length=8)),
                ('block_number', models.IntegerField()),
                ('source', models.CharField(max_length=42)),
                ('time', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30)),
                ('isError', models.BooleanField(default=False)),
                ('gasfee', models.DecimalField(blank=True, decimal_places=20, max_digits=38, null=True)),
                ('gas', models.IntegerField(blank=True, null=True)),
                ('sender', models.CharField(blank=True, max_length=42, null=True)),
                ('receiver', models.CharField(blank=True, max_length=42, null=True)),
                ('hash', models.CharField(blank=True, max_length=66, null=True)),
                ('token_name', models.CharField(blank=True, max_length=30, null=True)),
                ('token_symbol', models.CharField(blank=True, max_length=30, null=True)),
                ('token_decimal', models.IntegerField(blank=True, null=True)),
                ('exchange', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wallets')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
