# Generated by Django 4.2.1 on 2023-08-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_wallettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettoken',
            name='token',
            field=models.CharField(max_length=20),
        ),
    ]
