# Generated by Django 4.2.1 on 2023-08-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_wallettoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettoken',
            name='token',
            field=models.CharField(max_length=50),
        ),
    ]
