# Generated by Django 4.2.1 on 2023-08-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_wallettoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgers',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='ledgers/'),
        ),
    ]
