# Generated by Django 4.2.1 on 2023-08-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_wallettoken_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCompareAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('asset_name', models.CharField(max_length=20, unique=True)),
                ('asset_symbol', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='wallettoken',
            name='is_asset_price',
            field=models.BooleanField(default=False),
        ),
    ]
