# Generated by Django 4.2.1 on 2023-08-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cryptocompareassets_wallettoken_is_asset_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgers',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='ledgers/'),
        ),
    ]
