# Generated by Django 4.2.1 on 2023-08-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_transactions_contract_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletssort',
            name='contract_address',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
