# Generated by Django 4.2.1 on 2023-08-12 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_ledgers_file'),
        ('api', '0014_alter_cryptocompareassets_contract_address'),
    ]

    operations = [
    ]
